language: node_js
node_js: 'lts/*'
install:
  - npm install now -g
script:
  - yarn run scale-down
  - yarn run deploy
  - yarn run alias
  - yarn run scale-up
  - yarn run unalias
if: branch = master AND type IN (push)
